# -*- coding: utf-8 -*-
"""Anomaly Detection DBSCAN & PCA..ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZabAGG-unu_rX0hyzyyJBajrcWjiMlAs

Impor Library
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import DBSCAN
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

"""Unggah dan Baca Dataset"""

from google.colab import files
import pandas as pd

uploaded = files.upload()
filename = list(uploaded.keys())[0]
df = pd.read_csv('Dataset_Obesity.csv')
df.head()

"""Pilih Fitur yang Digunakan untuk Analisis"""

selected_columns = ['FCVC', 'CH2O']
data = df[selected_columns].dropna()
X_raw = data.values

"""DETEKSI ANOMALI DENGAN DBSCAN"""

dbscan = DBSCAN(eps=0.8, min_samples=5)
labels = dbscan.fit_predict(X_raw)

plt.figure(figsize=(8,6))
unique_labels = set(labels)
for label in unique_labels:
    mask = labels == label
    plt.scatter(X_raw[mask, 0], X_raw[mask, 1],
                label='Anomaly' if label == -1 else f'Cluster {label}',
                marker='x' if label == -1 else 'o')
plt.title("DBSCAN Anomaly Detection")
plt.xlabel("Feature 1")
plt.ylabel("Feature 2")
plt.legend()
plt.grid(True)
plt.show()

"""DETEKSI ANOMALI DENGAN PCA"""

# Standardize the data before PCA
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_raw)

# Apply PCA to reduce to 2 components
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)

# Use the length of the PCA projection as an anomaly score
anomaly_scores = np.linalg.norm(X_pca, axis=1)

# Define threshold for anomaly (top 5% highest scores)
threshold = np.percentile(anomaly_scores, 95)
y_pred_pca = anomaly_scores < threshold

plt.figure(figsize=(8, 6))

# Titik normal
plt.scatter(X_pca[y_pred_pca, 0], X_pca[y_pred_pca, 1],
            c='blue', label='Normal', edgecolor='k', s=60)

# Titik anomali
plt.scatter(X_pca[~y_pred_pca, 0], X_pca[~y_pred_pca, 1],
            c='red', label='Anomaly', edgecolor='k', s=60)

plt.title("Anomaly Detection using PCA Projection")
plt.xlabel("Feature 1")
plt.ylabel("Feature 2")
plt.legend()
plt.grid(True)
plt.show()