# -*- coding: utf-8 -*-
"""SGDClassifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18Ijg3sltq8SJ_dqNnstvnSf2D4GuL8rw

Sampling Method(Sliding Window)
"""

import pandas as pd
import numpy as np
import time
from sklearn.linear_model import SGDClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score

from google.colab import files
uploaded = files.upload()

df = pd.read_csv("Dataset_Obesity.csv")
df = df.dropna()

# Bagian 1: Preprocessing

X = df.drop('NObeyesdad', axis=1)
y = df['NObeyesdad']

for col in X.select_dtypes(include='object').columns:
    le = LabelEncoder()
    X[col] = le.fit_transform(X[col])

y = LabelEncoder().fit_transform(y)

# Standardisasi fitur
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Bagian 2: Sliding Window Setup

window_size = 100
step_size = 50
max_index = len(X)

model = SGDClassifier(loss='log_loss', random_state=42)
classes = np.unique(y)
first_fit = True

# Bagian 3: Loop Sliding Window dan Training

for start in range(0, max_index - window_size + 1, step_size):
    end = start + window_size
    buffer_x = X[start:end]
    buffer_y = y[start:end]

    X_train, X_test, y_train, y_test = train_test_split(
        buffer_x, buffer_y, test_size=0.2, random_state=42
    )

    if first_fit:
        model.partial_fit(X_train, y_train, classes=classes)
        first_fit = False
    else:
        model.partial_fit(X_train, y_train)

    y_pred = model.predict(X_test)
    acc = accuracy_score(y_test, y_pred)

    print(f"Window {start}-{end}: Accuracy = {acc:.2f}")
    time.sleep(0.2)
print("Sliding Window Training Completed.")

"""Incremental Learning (stochastic gradient descent)"""

import pandas as pd
import numpy as np
import time
from sklearn.linear_model import SGDClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score

df = pd.read_csv("Dataset_Obesity.csv")
df = df.dropna()

# Bagian 1: Setup batch dan model
batch_size = 100
n_batches = len(X) // batch_size

X_total, X_test, y_total, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = SGDClassifier(loss="log_loss", random_state=42)
classes = np.unique(y)

# Bagian 2: Loop per batch (incremental training)
for i in range(0, len(X_total), batch_size):
    X_batch = X_total[i:i + batch_size]
    y_batch = y_total[i:i + batch_size]

    if len(X_batch) == 0:
        continue

    if i == 0:
        model.partial_fit(X_batch, y_batch, classes=classes)
    else:
        model.partial_fit(X_batch, y_batch)

    batch_num = i // batch_size + 1
    total_batches = (len(X_total) + batch_size - 1) // batch_size
    print(f"Batch {batch_num}/{total_batches} trained")
    time.sleep(0.2)

# Bagian 3: Evaluasi Akhir
y_pred = model.predict(X_test)
acc = accuracy_score(y_test, y_pred)
print(f"Final Accuracy: {acc:.2f}")